# Generated by Django 4.0.6 on 2022-07-27 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eventconfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventname', models.TextField(max_length=50)),
                ('guild', models.PositiveBigIntegerField()),
                ('channel', models.PositiveBigIntegerField()),
                ('pingrole', models.PositiveBigIntegerField()),
                ('time_in_channel', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
