# Generated by Django 4.0.6 on 2022-07-28 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventconfigurations', '0003_alter_eventconfiguration_eventname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clanconfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guild', models.PositiveBigIntegerField()),
                ('clan', models.TextField(max_length=200)),
            ],
        ),
        migrations.AddConstraint(
            model_name='clanconfig',
            constraint=models.UniqueConstraint(fields=('guild', 'clan'), name='unique_clanconfig'),
        ),
    ]
