# Generated by Django 4.1 on 2023-02-18 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "player",
                    models.TextField(max_length=50, primary_key=True, serialize=False),
                ),
                ("lastonline", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Chest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("player", models.TextField(max_length=50)),
                ("location", models.TextField(max_length=80)),
                ("date", models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Encounter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("player", models.TextField(max_length=50)),
                ("pokemon", models.TextField(max_length=50)),
                ("date", models.DateField(auto_now=True)),
                ("level", models.PositiveSmallIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Eventname",
            fields=[
                (
                    "name",
                    models.TextField(max_length=50, primary_key=True, serialize=False),
                ),
                ("fields", models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name="Honeylocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location", models.TextField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name="Roll",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("player", models.TextField(max_length=50)),
                ("pokemon", models.TextField(max_length=50)),
                ("date", models.DateField(auto_now=True)),
                ("level", models.PositiveSmallIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Tournamentprize",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prize", models.TextField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name="Worldboss",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pokemon", models.TextField()),
                ("location", models.TextField()),
                ("date", models.DateField(auto_now=True)),
                ("participants", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Worldbosslocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location", models.TextField(max_length=80)),
            ],
        ),
    ]
