# Generated by Django 4.1 on 2023-02-11 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingame_data", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="worldboss",
            name="location",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
