# Generated by Django 4.1 on 2023-10-31 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingame_data', '0002_alter_chest_date_alter_encounter_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Onlinelist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('onlineAmount', models.PositiveSmallIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
