# Generated by Django 4.1 on 2023-11-26 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingame_data', '0003_onlinelist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(default=dict)),
                ('time', models.DateTimeField()),
                ('eventname', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ingame_data.eventname')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
