# Generated by Django 4.1 on 2023-02-18 16:47

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.text


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ingame_data", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Clanconfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("guild", models.PositiveBigIntegerField()),
                ("clan", models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="EventconfigPermissions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("guild", models.PositiveBigIntegerField()),
                ("role", models.PositiveBigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Eventconfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("guild", models.PositiveBigIntegerField()),
                ("channel", models.PositiveBigIntegerField(null=True)),
                ("pingrole", models.PositiveBigIntegerField(null=True)),
                ("time_in_channel", models.PositiveSmallIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Playerconfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("guild", models.PositiveBigIntegerField()),
                ("player", models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="PmConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user", models.PositiveBigIntegerField()),
                ("data", models.JSONField()),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="ingame_data.eventname",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="playerconfig",
            constraint=models.UniqueConstraint(
                models.OrderBy(
                    django.db.models.functions.text.Lower("player"), descending=True
                ),
                models.F("player"),
                name="unique_playerconfig",
            ),
        ),
        migrations.AddField(
            model_name="eventconfiguration",
            name="eventname",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="ingame_data.eventname"
            ),
        ),
        migrations.AddConstraint(
            model_name="eventconfigpermissions",
            constraint=models.UniqueConstraint(
                fields=("guild", "role"), name="unique_permissionconfig"
            ),
        ),
        migrations.AddConstraint(
            model_name="clanconfig",
            constraint=models.UniqueConstraint(
                models.OrderBy(
                    django.db.models.functions.text.Lower("clan"), descending=True
                ),
                models.F("guild"),
                name="unique_clanconfig",
            ),
        ),
        migrations.AddConstraint(
            model_name="pmconfig",
            constraint=models.UniqueConstraint(
                fields=("event", "user", "data"), name="unique_pmevents"
            ),
        ),
        migrations.AddConstraint(
            model_name="eventconfiguration",
            constraint=models.UniqueConstraint(
                fields=("guild", "eventname"), name="unique_events"
            ),
        ),
    ]
