# Generated by Django 4.1 on 2023-03-04 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventconfigurations", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="playerconfig", name="unique_playerconfig",
        ),
        migrations.AddConstraint(
            model_name="playerconfig",
            constraint=models.UniqueConstraint(
                fields=("player", "guild"), name="unique_playerconfig"
            ),
        ),
    ]
