# Generated by Django 4.1 on 2023-10-10 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventconfigurations', '0002_remove_playerconfig_unique_playerconfig_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventconfiguration',
            name='failed_sends',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
