# Generated by Django 4.0.6 on 2022-08-08 15:56

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('highscores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HighscoreConfig',
            fields=[
                ('highscorename', models.TextField(primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('pagesamount', models.PositiveSmallIntegerField()),
                ('fields', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
            ],
        ),
        migrations.AlterField(
            model_name='highscore',
            name='highscore',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='highscores.highscoreconfig'),
        ),
    ]
