# Generated by Django 4.0.6 on 2022-08-08 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('highscores', '0003_highscoreconfig_fieldmapping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highscoreconfig',
            name='fieldmapping',
            field=models.JSONField(),
        ),
    ]
