# Generated by Django 4.0.6 on 2022-08-08 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('highscores', '0004_alter_highscoreconfig_fieldmapping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='highscoreconfig',
            name='fields',
        ),
    ]
