# Generated by Django 4.0.6 on 2022-08-08 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('highscores', '0005_remove_highscoreconfig_fields'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='highscore',
            constraint=models.UniqueConstraint(fields=('rank', 'highscore'), name='unique_highscoreranks'),
        ),
    ]
