# Generated by Django 4.0.6 on 2022-08-12 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('highscores', '0006_highscore_unique_highscoreranks'),
    ]

    operations = [
        migrations.AddField(
            model_name='highscoreconfig',
            name='verbose_name',
            field=models.TextField(default=''),
        ),
    ]
