# Generated by Django 4.0.6 on 2022-07-28 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Encounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playername', models.TextField(max_length=50)),
                ('pokemon', models.TextField(max_length=50)),
                ('date', models.DateField()),
            ],
        ),
    ]
