# Generated by Django 4.0.6 on 2022-07-29 19:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingame_data', '0007_alter_activity_lastonline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='lastonline',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
