# Generated by Django 4.0.6 on 2022-07-29 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingame_data', '0008_alter_activity_lastonline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='lastonline',
            field=models.DateTimeField(),
        ),
    ]
